### ISSUE TITLE
feat(linter): Support lint the `<script>` part of Vue file

### ISSUE THREAD

**Issue by mysteryven** [oxc-project/oxc#1238]
Since we have VSCode plugin and more and more rules, is it time to support lint the `<script>` part of Vue file?

**Comment by Boshen** [comment]
It should be easy if you can figure out how to get the `<script>` part? Probably a super simple parser?

**Comment by Boshen** [comment]
Done!

**Comment by Hebilicious** [comment]
@Boshen As mainly a vue user, thank you for this, will definitely take it for a spin !

How hard would it be to support the script part of Svelte files ?
It might be harder because of the weird svelte syntax, but would it be safe to assume that for [svelte 5](https://svelte.dev/blog/runes#simpler-times-ahead) (which can be written without the weird syntax), it should work without much effort ? 

The reason I'm asking is because I'm working on SvelteKit project for work and the linting is painfully slow.

**Comment by Boshen** [comment]
@Hebilicious Can you take v0.1.2 a spin (with svelte support)? https://github.com/oxc-project/oxc/releases/tag/oxlint_v0.1.2

**Comment by Hebilicious** [comment]
Damn that was fast 👌 Thank you so much for all the hardwork !
