### ISSUE TITLE
Minifier should constant fold bindings

### ISSUE THREAD

**Issue by bmeck** [oxc-project/oxc#2129]
Given

```mjs
var OK = 200;
// ...
if (res.status === OK) {
//  ...
}
```

The minifier should replace read access to `OK` with the constant value of `200` if the total number of replacements would save space (in this case 1 additional char per `200` vs `OK` vs savings of removing `var OK = 200;`).

```mjs
if (res.status === 200) {
//  ...
}
```

Doing so should work even when the constant occurs after closures using it (with potential need for TDZ checks):

```mjs
function onResult() {
  if (res.status === OK) // ...
}
let OK = 200;
```

The minifier should apply this to any binding with a known constant value including `var`, `let`, `const`, etc.

**Comment by Boshen** [comment]
Here's my approach for this kind of thing, since I'm not an expert.

From the very beginning I decided to port most of google closure compiler, so I start looking there by search for files with "inline", and I found a bunch of `Inline*.java` files, e.g.

* https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/FlowSensitiveInlineVariablesTest.java
* https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/InlineVariablesTest.java

And also implmentations:

* https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/FlowSensitiveInlineVariables.java
* https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/InlineVariables.java

Luckily there's even an algorithm for it:

* https://github.com/google/closure-compiler/blob/990043cbc1d0da34df2e615359a8f9582d4a9d84/src/com/google/javascript/jscomp/InlineVariables.java#L35-L69
* https://github.com/google/closure-compiler/blob/990043cbc1d0da34df2e615359a8f9582d4a9d84/src/com/google/javascript/jscomp/FlowSensitiveInlineVariables.java#L43-L56

For these classes, you'll see `class InlineVariables implements CompilerPass {` and `class FlowSensitiveInlineVariables implements CompilerPass, ScopedCallback {
`

This means that we should introduce more compiler (AST) passes to aid information gathering.

Please be aware that AST passes are really cheap in oxc, because they are memory arena linear scans, don't be afraid to use them.

**Comment by bmeck** [comment]
@Boshen this seems fine but some methods like `getAliasedVar` don't have a clear way to go from things like Semantic to the Expression holding the IdentifierReference.

**Comment by Boshen** [comment]
I'm not getting the question.

The algorithm is always:

1. in a previous pass - collect lots of data
2. in the final folding pass, look up the data and see it we can replace it 

In Inlinevariables.java, we see

```java
    @Override
    public void afterExitScope(NodeTraversal t, ReferenceMap referenceMap) {
      doInlinesForScope(t, referenceMap);
    }
```

And eventually

```java
    /** Inline an immutable variable into all of its references. */
    private void inlineWellDefinedVariable(Var v, Node value, List<Reference> refSet) {
      for (Reference r : refSet) {
        if (r.getNode() == v.getNameNode()) {
          removeDeclaration(r);
        } else if (r.isSimpleAssignmentToName()) {
          /*
           * This is the initialization.
           *
           * <p>Replace the entire assignment with just the value, and use the original value node
           * in case it contains references to variables that still require inlining.
           */
          inlineValue(r.getParent(), value.detach());
        } else {
          Node clonedValue = value.cloneTree();
          NodeUtil.markNewScopesChanged(clonedValue, compiler);
          inlineValue(r.getNode(), clonedValue);
        }
      }
    }
```

**Comment by Boshen** [comment]
So in our case I presume we have collected lots of data in a previous pass, i.e.

1. Semantic Pass - we have assigned ReferenceId to IdentifierReference
2. Inline Data Collection pass - we collect stats about identifier usages
3. In the final folding pass, in https://github.com/oxc-project/oxc/blob/3d184d56a8bd54514560a01ec2dc64538732089b/crates/oxc_ast/src/visit_mut.rs#L1233-L1237

We check ReferenceId in our collected data and act accordingly.

This is really similar to the mangler, we there is a data collection pass on the scopes - https://github.com/oxc-project/oxc/blob/main/crates/oxc_minifier/src/mangler/mod.rs
