### ISSUE TITLE
[oxc_semantics] Improper return register when `finally` block throws

### ISSUE THREAD

**Issue by TzviPM** [oxc-project/oxc#2240]
Consider the following code:

```js
function not_foo() {
    try {
        try {
            return "foo";
        } finally {
            throw "foo";
        }
    } catch (e) {
        // do nothing
    }
}
```

What should the return value of this function be?

## According to the ES Spec:

The `try` statement runtime semantics are defined at https://tc39.es/ecma262/#sec-try-statement-runtime-semantics-evaluation:

1. Evaluate the outer try statement's block into `B`:
    1. Evaluate the inner try statement's block into `B`:
        1. The `SV` of `"foo"` is `"foo"` as per https://tc39.es/ecma262/#sec-static-semantics-sv
        2. Return `{ [[Type]]: RETURN, [[Value]]: "foo", [[Target]]: EMPTY }` as per https://tc39.es/ecma262/#sec-return-statement-runtime-semantics-evaluation
    2. Evaluate the inner try statement's finally block into `F`:
        1. The `SV` of `"foo"` is `"foo"` as per https://tc39.es/ecma262/#sec-static-semantics-sv
        2. Return `{ [[Type]]: THROW, [[Value]]: "foo", [[Target]]: EMPTY }` as per https://tc39.es/ecma262/#sec-throw-statement-runtime-semantics-evaluation
    3. Since, `F` is not a `normal completion`, do not set `F` to `B`.
    4. Since `F` is a `throw completion`, its value is not `EMPTY` as per https://tc39.es/ecma262/#sec-updateempty, so return `F`
2. Since `B` is a throw completion, let `C` be the result of the catch block with `e` bound to `"foo"`:
  1. Since the block is empty, return `EMPTY` as per https://tc39.es/ecma262/#sec-block-runtime-semantics-evaluation
  2. As per https://tc39.es/ecma262/#sec-implicit-normal-completion, `return EMPTY` is actually an editorial error and should be taken to mean `NormalCompletion(EMPTY)`.
  3. Return `{ [[Type]]: NORMAL, [[Value]]: EMPTY, [[Target]]: EMPTY }`
3. Since `C` has a value of `EMPTY`, return  `{ [[Type]]: NORMAL, [[Value]]: undefined, [[Target]]: EMPTY }` as per https://tc39.es/ecma262/#sec-updateempty

When calling `foo()`, the result is technically implementation-defined (i.e. not part of the ES spec), but the standard behaviour, since `foo` results in a `normal completion` would be to return `undefined` as per https://tc39.es/ecma262/#sec-ecmascript-function-objects-call-thisargument-argumentslist.

## The problem in our current CFG:

We store return values into a register called `$return`:

1. Since the outer try statement is a `try-catch`, we set the `after_throw` block to a reserved `catch` block.
2. In the inner `try` block, we set register to `"foo"`.
3. after the `try` block completes, there is `Normal` edge going to the `finally` block.
4. The finally block throws, so there is an outgoing edge to the `after_throw` block (in this case, the `catch`).
5. The catch block completes normally

We see, thus, that the end result of the CFG flow leads to a value of `"foo"` in the `$return` register.

## Solution space
One option is to somehow unset the `return` register when a finally block issues a `throw`. The problem with this is:

```js
function not_foo() {
    try {
        return "foo"
    } finally {
        try {
            try {
                return "bar";
            } finally {
                throw "foo";
            }
        } catch {
            // do nothing
        }
    }
}
```

In this code, the throw from the innermost `finally` causes its `try`'s `"bar"` return value to be unset, but since the `catch` squashes this, the outermost `finally` is a normal completion, and thus this entire statement should still return `"foo"`.

Another approach would be to ditch the idea of a `$return` register and instead manage completion records more rigorously.

**Comment by bmeck** [comment]
I'd note the result is not implementation defined, per https://tc39.es/ecma262/#sec-try-statement-runtime-semantics-evaluation invoking [UpdateEmpty](https://tc39.es/ecma262/#sec-updateempty)(C, undefined).

**Comment by TzviPM** [comment]
> I'd note the result is not implementation defined, per https://tc39.es/ecma262/#sec-try-statement-runtime-semantics-evaluation invoking [UpdateEmpty](https://tc39.es/ecma262/#sec-updateempty)(C, undefined).

By implementation defined, I meant that the actual `[[Call]]` function's internal block is not guaranteed by the spec to do anything specific. The result of the function is defined to be the result of `F.[[Call]]` applied to the normal completion with `[[Value]]` set to `Empty`. I'm not aware of any implementation in which that result is not `undefined`, and certainly the reference algorithm in section 10 works that way.

**Comment by TzviPM** [comment]
This was based on my understanding of https://tc39.es/ecma262/#sec-object-internal-methods-and-internal-slots, although I imagine I'm reading it incorrectly.

**Comment by bmeck** [comment]
@TzviPM I think https://tc39.es/ecma262/#sec-ecmascript-function-objects-call-thisargument-argumentslist might be what you are meaning to get to at 10.2.1.10 ?

**Comment by TzviPM** [comment]
Ah, I see: https://tc39.es/ecma262/#sec-ecmascript-function-objects

> An ECMAScript [function object](https://tc39.es/ecma262/#function-object) is an [ordinary object](https://tc39.es/ecma262/#ordinary-object) and has the same internal slots and the same internal methods as other [ordinary objects](https://tc39.es/ecma262/#ordinary-object).

In https://tc39.es/ecma262/#sec-object-internal-methods-and-internal-slots:
> An ordinary object is an object that satisfies all of the following criteria:
> ...
> If the object has a [[Call]] internal method, it uses either the one defined in [10.2.1](https://tc39.es/ecma262/#sec-ecmascript-function-objects-call-thisargument-argumentslist) or the one defined in [10.3.1](https://tc39.es/ecma262/#sec-built-in-function-objects-call-thisargument-argumentslist).

The semantics for a function call are in https://tc39.es/ecma262/#sec-function-calls-runtime-semantics-evaluation. The [EvaluateCall](https://tc39.es/ecma262/#sec-evaluatecall) semantics defers to [Call](https://tc39.es/ecma262/#sec-call) which in turn results in `F.[[Call]](V, argumentsList)`. What I missed is that "F is the [function object](https://tc39.es/ecma262/#function-object)" and so the `[[Call]]` block is guaranteed to be the one you mentioned. Technically, it should be possible to have an exotic function object that behaves differently.

**Comment by bmeck** [comment]
@TzviPM correct, though I don't know of an engine that allows for it to do so even with exotic host objects.

**Comment by rzvxa** [comment]
I suspect it is fixed in our new CFG implementation since we don't use registers anymore instead we are creating a simple control flow pointing to appropriate AST nodes.

For this code:
```js
function not_foo() {
    try {
        try {
            return "foo";
        } finally {
            throw "foo";
        }
    } catch (e) {
        // do nothing
    }
}
```
Now we have this flow: [CFG Visualization](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0A%20%20%20%200%20%5B%20xlabel%20%3D%20%22nodes0%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb0%0A%22%5D%0A%20%20%20%201%20%5B%20xlabel%20%3D%20%22nodes1%20%5BProgram%5D%5Cl%22%2C%20label%20%3D%20%22bb1%0A%22%5D%0A%20%20%20%202%20%5B%20xlabel%20%3D%20%22nodes2%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb2%0A%22%5D%0A%20%20%20%203%20%5B%20xlabel%20%3D%20%22nodes3%20%5B%5Cl%20%20%20%20Function(not_foo)%5Cl%20%20%20%20BindingIdentifier(not_foo)%5Cl%20%20%20%20FormalParameters%5Cl%20%20%20%20FunctionBody%5Cl%20%20%20%20TryStatement%5Cl%5D%5Cl%22%2C%20label%20%3D%20%22bb3%0ATryStatement%22%5D%0A%20%20%20%204%20%5B%20xlabel%20%3D%20%22nodes4%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb4%0A%22%5D%0A%20%20%20%205%20%5B%20xlabel%20%3D%20%22nodes5%20%5B%5Cl%20%20%20%20BlockStatement%5Cl%20%20%20%20TryStatement%5Cl%5D%5Cl%22%2C%20label%20%3D%20%22bb5%0ABlockStatement%0ATryStatement%22%5D%0A%20%20%20%206%20%5B%20xlabel%20%3D%20%22nodes6%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb6%0A%22%5D%0A%20%20%20%207%20%5B%20xlabel%20%3D%20%22nodes7%20%5B%5Cl%20%20%20%20BlockStatement%5Cl%20%20%20%20ReturnStatement%5Cl%20%20%20%20StringLiteral(foo)%5Cl%5D%5Cl%22%2C%20label%20%3D%20%22bb7%0ABlockStatement%0Areturn%20%3Cvalue%3E%22%5D%0A%20%20%20%208%20%5B%20xlabel%20%3D%20%22nodes8%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb8%0Aunreachable%22%5D%0A%20%20%20%209%20%5B%20xlabel%20%3D%20%22nodes9%20%5B%5Cl%20%20%20%20FinallyClause%5Cl%20%20%20%20ThrowStatement%5Cl%20%20%20%20StringLiteral(foo)%5Cl%5D%5Cl%22%2C%20label%20%3D%20%22bb9%0Athrow%22%5D%0A%20%20%20%2010%20%5B%20xlabel%20%3D%20%22nodes10%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb10%0Aunreachable%22%5D%0A%20%20%20%2011%20%5B%20xlabel%20%3D%20%22nodes11%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb11%0A%22%5D%0A%20%20%20%2012%20%5B%20xlabel%20%3D%20%22nodes12%20%5B%5Cl%20%20%20%20CatchClause%5Cl%20%20%20%20CatchParameter%5Cl%20%20%20%20BindingIdentifier(e)%5Cl%5D%5Cl%22%2C%20label%20%3D%20%22bb12%0A%22%5D%0A%20%20%20%2013%20%5B%20xlabel%20%3D%20%22nodes13%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb13%0A%22%5D%0A%20%20%20%2014%20%5B%20xlabel%20%3D%20%22nodes14%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb14%0A%22%5D%0A%20%20%20%201%20-%3E%200%20%5B%20label%20%3D%20%22Error(Implicit)%22%5D%0A%20%20%20%203%20-%3E%202%20%5B%20label%20%3D%20%22Error(Implicit)%22%5D%0A%20%20%20%201%20-%3E%203%20%5B%20label%20%3D%20%22NewFunction%22%5D%0A%20%20%20%205%20-%3E%204%20%5B%20label%20%3D%20%22Error(Explicit)%22%5D%0A%20%20%20%207%20-%3E%204%20%5B%20label%20%3D%20%22Error(Explicit)%22%5D%0A%20%20%20%207%20-%3E%206%20%5B%20label%20%3D%20%22Finalize%22%5D%0A%20%20%20%208%20-%3E%204%20%5B%20label%20%3D%20%22Error(Explicit)%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%208%20-%3E%206%20%5B%20label%20%3D%20%22Finalize%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%207%20-%3E%208%20%5B%20label%20%3D%20%22Unreachable%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%209%20-%3E%204%20%5B%20label%20%3D%20%22Error(Explicit)%22%5D%0A%20%20%20%206%20-%3E%209%20%5B%20label%20%3D%20%22Normal%22%5D%0A%20%20%20%2010%20-%3E%204%20%5B%20label%20%3D%20%22Error(Explicit)%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%209%20-%3E%2010%20%5B%20label%20%3D%20%22Unreachable%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%2011%20-%3E%204%20%5B%20label%20%3D%20%22Error(Explicit)%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%205%20-%3E%207%20%5B%20label%20%3D%20%22Normal%22%5D%0A%20%20%20%2010%20-%3E%2011%20%5B%20label%20%3D%20%22Unreachable%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%2012%20-%3E%202%20%5B%20label%20%3D%20%22Error(Implicit)%22%5D%0A%20%20%20%204%20-%3E%2012%20%5B%20label%20%3D%20%22Normal%22%5D%0A%20%20%20%2013%20-%3E%202%20%5B%20label%20%3D%20%22Error(Implicit)%22%5D%0A%20%20%20%203%20-%3E%205%20%5B%20label%20%3D%20%22Normal%22%5D%0A%20%20%20%2011%20-%3E%2013%20%5B%20label%20%3D%20%22Normal%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%2012%20-%3E%2013%20%5B%20label%20%3D%20%22Normal%22%5D%0A%20%20%20%2014%20-%3E%200%20%5B%20label%20%3D%20%22Error(Implicit)%22%5D%0A%20%20%20%201%20-%3E%2014%20%5B%20label%20%3D%20%22Normal%22%5D%0A%7D%0A)

And for this:

```js
function not_foo() {
    try {
        return "foo"
    } finally {
        try {
            try {
                return "bar";
            } finally {
                throw "foo";
            }
        } catch {
            // do nothing
        }
    }
}
```

We get this flow: [CFG Visaulization](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0A%20%20%20%200%20%5B%20xlabel%20%3D%20%22nodes0%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb0%0A%22%5D%0A%20%20%20%201%20%5B%20xlabel%20%3D%20%22nodes1%20%5BProgram%5D%5Cl%22%2C%20label%20%3D%20%22bb1%0A%22%5D%0A%20%20%20%202%20%5B%20xlabel%20%3D%20%22nodes2%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb2%0A%22%5D%0A%20%20%20%203%20%5B%20xlabel%20%3D%20%22nodes3%20%5B%5Cl%20%20%20%20Function(not_foo)%5Cl%20%20%20%20BindingIdentifier(not_foo)%5Cl%20%20%20%20FormalParameters%5Cl%20%20%20%20FunctionBody%5Cl%20%20%20%20TryStatement%5Cl%5D%5Cl%22%2C%20label%20%3D%20%22bb3%0ATryStatement%22%5D%0A%20%20%20%204%20%5B%20xlabel%20%3D%20%22nodes4%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb4%0A%22%5D%0A%20%20%20%205%20%5B%20xlabel%20%3D%20%22nodes5%20%5B%5Cl%20%20%20%20BlockStatement%5Cl%20%20%20%20ReturnStatement%5Cl%20%20%20%20StringLiteral(foo)%5Cl%5D%5Cl%22%2C%20label%20%3D%20%22bb5%0ABlockStatement%0Areturn%20%3Cvalue%3E%22%5D%0A%20%20%20%206%20%5B%20xlabel%20%3D%20%22nodes6%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb6%0Aunreachable%22%5D%0A%20%20%20%207%20%5B%20xlabel%20%3D%20%22nodes7%20%5B%5Cl%20%20%20%20FinallyClause%5Cl%20%20%20%20TryStatement%5Cl%5D%5Cl%22%2C%20label%20%3D%20%22bb7%0ATryStatement%22%5D%0A%20%20%20%208%20%5B%20xlabel%20%3D%20%22nodes8%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb8%0A%22%5D%0A%20%20%20%209%20%5B%20xlabel%20%3D%20%22nodes9%20%5B%5Cl%20%20%20%20BlockStatement%5Cl%20%20%20%20TryStatement%5Cl%5D%5Cl%22%2C%20label%20%3D%20%22bb9%0ABlockStatement%0ATryStatement%22%5D%0A%20%20%20%2010%20%5B%20xlabel%20%3D%20%22nodes10%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb10%0A%22%5D%0A%20%20%20%2011%20%5B%20xlabel%20%3D%20%22nodes11%20%5B%5Cl%20%20%20%20BlockStatement%5Cl%20%20%20%20ReturnStatement%5Cl%20%20%20%20StringLiteral(bar)%5Cl%5D%5Cl%22%2C%20label%20%3D%20%22bb11%0ABlockStatement%0Areturn%20%3Cvalue%3E%22%5D%0A%20%20%20%2012%20%5B%20xlabel%20%3D%20%22nodes12%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb12%0Aunreachable%22%5D%0A%20%20%20%2013%20%5B%20xlabel%20%3D%20%22nodes13%20%5B%5Cl%20%20%20%20FinallyClause%5Cl%20%20%20%20ThrowStatement%5Cl%20%20%20%20StringLiteral(foo)%5Cl%5D%5Cl%22%2C%20label%20%3D%20%22bb13%0Athrow%22%5D%0A%20%20%20%2014%20%5B%20xlabel%20%3D%20%22nodes14%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb14%0Aunreachable%22%5D%0A%20%20%20%2015%20%5B%20xlabel%20%3D%20%22nodes15%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb15%0A%22%5D%0A%20%20%20%2016%20%5B%20xlabel%20%3D%20%22nodes16%20%5BCatchClause%5D%5Cl%22%2C%20label%20%3D%20%22bb16%0A%22%5D%0A%20%20%20%2017%20%5B%20xlabel%20%3D%20%22nodes17%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb17%0A%22%5D%0A%20%20%20%2018%20%5B%20xlabel%20%3D%20%22nodes18%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb18%0A%22%5D%0A%20%20%20%2019%20%5B%20xlabel%20%3D%20%22nodes19%20%5BNone%5D%5Cl%22%2C%20label%20%3D%20%22bb19%0A%22%5D%0A%20%20%20%201%20-%3E%200%20%5B%20label%20%3D%20%22Error(Implicit)%22%5D%0A%20%20%20%203%20-%3E%202%20%5B%20label%20%3D%20%22Error(Implicit)%22%5D%0A%20%20%20%201%20-%3E%203%20%5B%20label%20%3D%20%22NewFunction%22%5D%0A%20%20%20%205%20-%3E%202%20%5B%20label%20%3D%20%22Error(Implicit)%22%5D%0A%20%20%20%205%20-%3E%204%20%5B%20label%20%3D%20%22Finalize%22%5D%0A%20%20%20%206%20-%3E%202%20%5B%20label%20%3D%20%22Error(Implicit)%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%206%20-%3E%204%20%5B%20label%20%3D%20%22Finalize%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%205%20-%3E%206%20%5B%20label%20%3D%20%22Unreachable%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%207%20-%3E%202%20%5B%20label%20%3D%20%22Error(Implicit)%22%5D%0A%20%20%20%204%20-%3E%207%20%5B%20label%20%3D%20%22Normal%22%5D%0A%20%20%20%209%20-%3E%208%20%5B%20label%20%3D%20%22Error(Explicit)%22%5D%0A%20%20%20%2011%20-%3E%208%20%5B%20label%20%3D%20%22Error(Explicit)%22%5D%0A%20%20%20%2011%20-%3E%2010%20%5B%20label%20%3D%20%22Finalize%22%5D%0A%20%20%20%2012%20-%3E%208%20%5B%20label%20%3D%20%22Error(Explicit)%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%2012%20-%3E%2010%20%5B%20label%20%3D%20%22Finalize%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%2011%20-%3E%2012%20%5B%20label%20%3D%20%22Unreachable%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%2013%20-%3E%208%20%5B%20label%20%3D%20%22Error(Explicit)%22%5D%0A%20%20%20%2010%20-%3E%2013%20%5B%20label%20%3D%20%22Normal%22%5D%0A%20%20%20%2014%20-%3E%208%20%5B%20label%20%3D%20%22Error(Explicit)%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%2013%20-%3E%2014%20%5B%20label%20%3D%20%22Unreachable%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%2015%20-%3E%208%20%5B%20label%20%3D%20%22Error(Explicit)%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%209%20-%3E%2011%20%5B%20label%20%3D%20%22Normal%22%5D%0A%20%20%20%2014%20-%3E%2015%20%5B%20label%20%3D%20%22Unreachable%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%2016%20-%3E%202%20%5B%20label%20%3D%20%22Error(Implicit)%22%5D%0A%20%20%20%208%20-%3E%2016%20%5B%20label%20%3D%20%22Normal%22%5D%0A%20%20%20%2017%20-%3E%202%20%5B%20label%20%3D%20%22Error(Implicit)%22%5D%0A%20%20%20%207%20-%3E%209%20%5B%20label%20%3D%20%22Normal%22%5D%0A%20%20%20%2015%20-%3E%2017%20%5B%20label%20%3D%20%22Normal%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%2016%20-%3E%2017%20%5B%20label%20%3D%20%22Normal%22%5D%0A%20%20%20%2018%20-%3E%202%20%5B%20label%20%3D%20%22Error(Implicit)%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%203%20-%3E%205%20%5B%20label%20%3D%20%22Normal%22%5D%0A%20%20%20%2017%20-%3E%2018%20%5B%20label%20%3D%20%22Unreachable%22%2C%20style%20%3D%20%22dotted%22%20%5D%0A%20%20%20%2019%20-%3E%200%20%5B%20label%20%3D%20%22Error(Implicit)%22%5D%0A%20%20%20%201%20-%3E%2019%20%5B%20label%20%3D%20%22Normal%22%5D%0A%7D%0A)

Both of which seems alright to me, I don't close this issue in case there is another issue I haven't noticed yet.

**Comment by rzvxa** [comment]
@TzviPM Would you also give this a look? There is no pressure since neither of these (this and #2312) is urgent.

**Comment by rzvxa** [comment]
@Boshen I think this can be close, Don't you think?
