### ISSUE TITLE
Make `Atom` safe and faster

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#2295]
`Atom` had a memory leak which is not desirable: https://github.com/oxc-project/oxc/issues/1803

I removed the memory and miri test to the parser: https://github.com/oxc-project/oxc/pull/2294

The change introduced some performance regressions and a unsafe

https://github.com/oxc-project/oxc/blob/6002560fa1398bc4bc68696e402e51c776f4ed53/crates/oxc_span/src/atom.rs#L103-L104

The next goal is to remove this unsafe.

**Comment by overlookmotel** [comment]
Can I tackle this? I already have a WIP which steals a lot of the efficient code of `CompactString`. @Boshen I know you're aware of that, but obviously you ran out of patience waiting for me (I don't blame you). I seem to have got side-tracked by trying to optimize the lexer!

But now that the memory leak is solved, perhaps it's a little less urgent?

**Comment by Boshen** [comment]
> That sound OK to you?

I can't wait! But take your time and enjoy the fun!

**Comment by Boshen** [comment]
Instead of exposing a single `Atom` type, I'm thinking along the lines of:

* `ArenaStr<'a>` with the functionaries of inlined string + arena allocated str
* `CompactStr` with the functionaries of inlined string + heap allocated str

The `ArenaStr<'a>` will have `to_compact_str` and `to_string` for downstream usages, the user has the choice of choosing the most convenient one for them.

**Comment by overlookmotel** [comment]
This is really nice - nice combination of efficiency and usability.

Just to check a couple of things:

`ArenaStr<'a>` is what will be used in the AST? `to_compact_str` / `to_string` are for downstream users, if they don't want to deal with lifetimes in their own code, or if they want to mutate the string?

I'm unclear how `ArenaStr<'a>` can be size of a `u32`. I was imagining `ArenaStr<'a>` being 16 bytes:

* Bytes 0-7: Pointer
* Bytes 8-11: Length (`u32`)
* Bytes 12-15: Unused (though could find uses for this e.g. index into Vec of escaped strings, or flags for "String is in source code" / "String is escaped" / "String is Unicode").

We could probably squeeze it down smaller using pointer compression, but:

1. That optimization could also apply to `Vec`s and `Box`s in the AST, so I was thinking of it as a broader issue.
2. 16 is probably a good size for making majority of strings be stored inline (most JS identifiers are under 16 bytes).

Or have I misunderstood, and you have something else in mind?

**Comment by Boshen** [comment]
> ArenaStr<'a> is what will be used in the AST?

Yes.

> ArenaStr<'a> can be size of a u32. I was imagining ArenaStr<'a> being 16 bytes

16 bytes would be even better! If you are able to shrink it down :-)

**Comment by Boshen** [comment]
Alright, we are going to solve this problem in a few steps:

1. refactor the `Atom` API without changing the implementation, i.e. add `CompactStr` and `to_compact_str`.
2. Change all downstream usages to use `CompactStr`, i.e. all crates other than the AST and parser crate should use `CompactStr`
3. Change `Atom` to `ArenaStr<'a>` within the ast and parser crates

**Comment by overlookmotel** [comment]
Sounds like a plan!

Do we need `CompactStr` to be mutable? If not, we could make our own version of `CompactStr` which has same size and layout as `ArenaStr`. It would only differ in where it stores out-of-line content for strings over 16 bytes (heap instead of reference to source text/arena).

Advantage of that would be that for strings under 16 bytes, converting from `ArenaStr<'a>` to `CompactStr` (or back) would be free - just `transmute`.

But if `CompactStr` needs to be mutable, this wouldn't work, as it'd require a `capacity` field.

**Comment by overlookmotel** [comment]
Sounds like a plan!

Do we need `CompactStr` to be mutable? If not, we could make our own version of `CompactStr` which has same size and layout as `ArenaStr`. It would only differ in where it stores out-of-line content for strings over 16 bytes (heap instead of reference to source text/arena).

Advantage of that would be that for strings under 16 bytes, converting from `ArenaStr<'a>` to `CompactStr` (or back) would be free - just `transmute`.

But if `CompactStr` needs to be mutable, this wouldn't work, as it'd require a `capacity` field.

**Comment by overlookmotel** [comment]
> 16 bytes would be even better! If you can shrink it down :-)

Yes, this is totally possible. Same size as `Box<str>`, and use `compact_str`'s trick of smuggling discriminant for inline/arena + inline length in the last byte (only byte values 0-191 are legal for last byte of a UTF-8 string, so you have values 192-255 free to represent other states).

**Comment by Boshen** [comment]
Continue on https://github.com/oxc-project/oxc/issues/2516
