### ISSUE TITLE
linter: eslint-plugin-vue

### ISSUE THREAD

**Issue by rkorzhoff** [oxc-project/oxc#2575]
Would be great to add support for Vue plugins and rule sets such as `eslint-plugin-vue`, `@vue/eslint-config-typescript`, `@vue/eslint-config-prettier`, etc❤️

**Comment by Boshen** [comment]
We currently lint the `<script>` parts of `.vue` files, linting other parts are not planned due to its complexity.

**Comment by armano2** [comment]
> We currently lint the `<script>` parts of `.vue` files, linting other parts are not planned due to its complexity.

q: if one did implementation for this, would you accept PR for this, parser/scope/visitor?

**Comment by rzvxa** [comment]
As far as the project roadmap goes, It isn't planned.

From here on I'm speaking for myself so take it with a grain of salt. If it is implemented nicely and in a performant way we probably accept it. However, due to maintenance burdens, we'll be conservative when it comes to merging such a sizable addition to the core codebase. It isn't just initial implementation that is preventing us from supporting it; There is also keeping it up to spec and putting resources toward battle-testing it.

Currently, we don't have any big downstream users who are looking for vue support; Having a consumer that'd invest in the implementation - via contributions, donations, and feedback - would definitely help the case.

**Comment by amritk** [comment]
Is this still the case with the void zero partnership?

**Comment by innocenzi** [comment]
> We are building a unified high-performance toolchain for JavaScript: including parser, transformer, resolver, linter, formatter, minifier, bundler, test runner, and meta framework support. Our mission is to make the next generation of JavaScript developers more productive than ever before. 

Getting rid of eslint completely in favor of OXC would be the dream, but Vue developers can't do that just yet. Hopefully, VoidZero changed that stance? 👀
