### ISSUE TITLE
Inline short functions with no side effects during minification

### ISSUE THREAD

**Issue by benmccann** [oxc-project/oxc#2647]
The Svelte 5 compiler will output code similar to what is in this playground:
https://oxc-project.github.io/oxc/playground/?code=3YCAAIC5g4CAgICAgICXCgAPv2ehA4IxBTvsjhRgWlWVDpHqL3D3Sk7O2KB8o2KYH0bpXoCSlaSIosraVjcMOJ1pIhtt07tH3yVuadC%2FYImPyUfbnQKqeFkqCO35iA60vhMkmTefxIC3b2M%2FCFIx4m2lavRWqw9XSwmZX9gZX%2FlEoRdlkYX9eeB9wwpWoX5aDEmCexUWU5%2BOqAj7k0reZ0FdajyIlvWhcQjMKkf7arV8HgSa18feG4ADNADEf9zdNf4BfFE063QQnHk6NHW2YND6ASJxuyKVywPbhtp1MsuwCrbmGPwDGHZN%2BcwO2DMtS2Z5om%2Fu4vUSJwHafiikGhtwZ89I0fDIeuSw3MP8QX5ThWRTApbOf2%2F4Tgk%3D

Things like:
```
div_1 = child(div), div_2 = child(div_1), div_3 = child(div_2)
```

Could be reduced to something along the lines of:
```
div.firstChild.firstChild.firstChild
```

**Comment by Boshen** [comment]
Thank you for the tests! Unfortunately the work on the minifier is currently stalled due to lack of resources.

**Comment by rzvxa** [comment]
@benmccann @Boshen is there a similar transformer from Babel or something that does this inlining optimization? Since inlining happens implicitly and javascript is such a dynamic language that can have unexpected stuff happening to it at runtime, Where should be the crossing point for inlining?
Is it really safe? what if that function gets called using a string and index operator?

**Comment by benmccann** [comment]
Hmm. Good point.

One other idea would be to instead of outputting`a=c(d),a=c(a),a=c(a)` to output `a=c(c(c(d)))`, but that seems like a separate issue, so perhaps we should close this one

**Comment by Boshen** [comment]
We don't have the bandwidth to work on the minifier right now, we'll revisit this when we are able to.
