### ISSUE TITLE
`AssignmentTargetRest` should have `argument` field in JSON AST

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#2657]
@ArnaudBarre said on https://github.com/oxc-project/oxc/pull/2652#issuecomment-1987009066 (relevant to #2463):

The manual `AssignmentTargetRest` should be updated to use `argument` field.

**Comment by overlookmotel** [comment]
> The manual `AssignmentTargetRest` should be updated to use `argument` field.

Thanks for spotting this. Damn! I thought I'd got it all correct in the end (and it was a bit of a battle).

I struggled a bit because I wasn't sure what AST type was our target for what we're trying to match. I was comparing to Acorn's output as produced by https://ast.sxzz.moe/ but that doesn't include the TS-related fields. What parser are we comparing to, and is that parser's output available on any playground/AST explorer?

On this specific one, could you possibly provide some source code which produces the incorrect AST? From looking at the Serde impls, it should already be renaming the `target` field to `argument`.

https://github.com/oxc-project/oxc/blob/32303b20fb54aafa60138c7133e31429d2421df5/crates/oxc_ast/src/ast/js.rs#L1040-L1045

Probably I'm missing something...

**Comment by ArnaudBarre** [comment]
For now I'm trying to match `@typescript-eslint/parser` because it's the default prettier parser. It's almost identical to Babel with `typescript` & `estree` plugins, but I found some subtitle variations like for #2654 & #2574. In both cases, I think the TSESLint team have done a good job at making an ESTree version that follow the TS syntax updates. I'm using `https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/ast-spec` to look at type definitions. I'm also using https://ast.sxzz.moe/ now

**Comment by overlookmotel** [comment]
@ArnaudBarre Ah I think I get it now. To confirm: You were saying the *TS type* for `AssignmentTargetRest` is wrong, not the actual JSON AST node?

If so, then #2668 should fix that. But if not please let me know.

**Comment by ArnaudBarre** [comment]
Yep sorry for the confusion, it was only types that were wrong, not actual tree. This was just this one line change this why I didn't want or interfer with your work on rest elements.

The other type issue a bit more complex is that the `type` property is missing in the types (but present in the AST) for:
- ObjectPattern
- ArrayPattern
- FormalParameters
- ArrayAssignmentTarget
- ObjectAssignmentTarget

**Comment by overlookmotel** [comment]
Fixed in #2668.
