### ISSUE TITLE
doc(cli): You have to specify the directory, not wildcards.

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#2695]
Well, found the problem. You have to specify the directory, not wildcards.
```
$ npx oxlint src/components
Finished in 8ms on 7 files with 87 rules using 12 threads.
Found 0 warnings and 0 errors.
```
Seems a problem specific to Windows that does not expand wildcards on the command line.
Maybe adding this to the documentation could help...

_Originally posted by @crystalfp in https://github.com/oxc-project/oxc/issues/1915#issuecomment-1991639303_

**Comment by bivihoba** [comment]
BTW this issue seems to be not only about Windows. In case of using `oxlint` command via npm scripts (because why not, it's pretty common for linters), the `path` option wouldn't work. Glob-argument for path, like `src/**/*.js` will not be transformed to an array.

Of course, the more reasonable and recommended way to run `oxlint` is via `lint-staged`, which does this dirty work with globs internally. 

However, the fact that it's required to keep in mind the inner features of execution context, could be a bit confusing from a user perspective.
