### ISSUE TITLE
Niche Optimization for `Option<ReferenceId>` and `IndexVec<ReferenceId, T>`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#3318]
we have these index types 

https://github.com/oxc-project/oxc/blob/712ee0dde8e03d79513b42bad3b6736b566dd60b/crates/oxc_syntax/src/reference.rs#L6-L8

https://github.com/oxc-project/oxc/blob/712ee0dde8e03d79513b42bad3b6736b566dd60b/crates/oxc_syntax/src/symbol.rs#L7-L9

where 

https://github.com/oxc-project/oxc/blob/712ee0dde8e03d79513b42bad3b6736b566dd60b/crates/oxc_ast/src/ast/js.rs#L451

https://github.com/oxc-project/oxc/blob/712ee0dde8e03d79513b42bad3b6736b566dd60b/crates/oxc_semantic/src/reference.rs#L22

can be trimmed by niche optimization.

But, 

```rust
use std::num::NonZeroU32;
define_index_type! {
    pub struct ReferenceId = NonZeroU32;
}
```

is not supported by the macro `define_index_type`

```
error[E0599]: no function or associated item named `max_value` found for struct `NonZero` in the current scope
   --> crates/oxc_syntax/src/reference.rs:7:1
    |
7   | / define_index_type! {
8   | |     pub struct ReferenceId = NonZeroU32;
9   | | }
    | |_^ function or associated item not found in `NonZero<u32>`
    |
note: if you're trying to build a new `NonZero<u32>` consider using one of the following associated functions:
      NonZero::<T>::new
      NonZero::<T>::new_unchecked
   --> /Users/boshen/.rustup/toolchains/1.78.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/num/nonzero.rs:308:5
```

but the good news is that we forked it and lives in https://github.com/oxc-project/oxc/tree/main/crates/oxc_index

The task of this issue is to make it work, if possible.

**Comment by overlookmotel** [comment]
### NonMaxU32

Personally, I am not a massive fan of the [nonmax crate](https://crates.io/crates/nonmax).

Unlike `NonZeroU32`, `nonmax::NonMaxU32` does not have native compiler support. It's basically a wrapper around `NonZeroU32` which and stores `n ^ u32::MAX`. So it has a (small) cost every time you use read or write it.

https://github.com/LPGhatguy/nonmax/blob/645abf30102dd880542865195c36893ee89994b5/src/lib.rs#L132-L137

This differs from the Rust's native `NonMaxU32` which uses `#[rustc_layout_scalar_valid_range_start(1)]`, which is not available in userland.

https://doc.rust-lang.org/stable/src/core/num/nonzero.rs.html#83-86

So unfortunately, there is no `NonMaxU32` type available to us which doesn't come with a cost.

This is unfortunate, but as we know Rust often moves at a glacial pace when it comes to stabilizing useful features.

### What we could do instead

Initialize our indexed `Vec`s with a dummy entry at index 0, so usable indexes start at 1.

Then 2 options:

1. Use `Option<NonZeroU32>`.
2. Use plain `u32` (no `Option`) and treat the value 0 as a sentinel meaning "not initialized".

Personally I favour option 2. I assume there must be code all over the place which reads these fields and then calls `unwrap()` on the `Option`, because we know semantic has run and filled in all the IDs. I doubt the compiler can prove that these `Option`s are never `None`, so it's likely producing unnecessary panicking branches all over the place in the code. Using plain `u32` should avoid that.

**Comment by overlookmotel** [comment]
There's also a much more complicated, but more performant solution.

As far as I'm aware, the `Vec`s which `ReferenceId`, `SymbolId` and `ScopeId` index into can only grow, never contract.

We could capitalize on this invariant to remove bounds checks. Something like:

```rs
pub struct ReferenceVec(Vec<Whatever>);
pub struct ReferenceId(u32);

impl ReferenceId {
  const EMPTY: Self = ReferenceId(0);
}

impl ReferenceVec {
  pub fn new() -> Self {
    // Initialize vec with a dummy at index 0
    let mut inner = Vec::new();
    inner.push(Whatever::default());
    Self(inner)
  }

  pub fn push(&mut self, value: Whatever) -> ReferenceId {
    self.0.push(value);
    ReferenceId(self.0.len())
  }

  // Returns `&Whatever` not `Option<&Whatever>`
  // because `ReferenceId` is always a valid index
  pub fn get(&mut self, index: ReferenceId) -> &Whatever {
    // `index` must be in bounds, so skip bounds check
    unsafe { self.0.get(index.0).unwrap_unchecked() }
  }

  // NB: No `pop` method
}
```

i.e. The only way to get a `ReferenceId` is via `push()`, and because `ReferenceVec` never shrinks, once you have a `ReferenceId`, it always remains valid. So no need for bounds check on `get()`.

Actual implementation would need to be more complex than the above. Would need some mechanism to ensure there can only be one `ReferenceVec` in existence at a time, and prevent you from keeping a `ReferenceId` from an old `ReferenceVec` and then using it on *another* `ReferenceVec`. But hopefully the above gives the general idea.

**Comment by Boshen** [comment]
It seems like you're proposing a new crate for this use case, instead of reusing the crates I found from the community.

**Comment by overlookmotel** [comment]
> It seems like you're proposing a new crate for this use case, instead of reusing the crates I found from the community.

I hope not! I thought the reason we swapped `index_vec` for our own `oxc_index` was so we could bend it to our use cases. I think @rzvxa had exactly the `NonZeroU32` use case in mind when he proposed bringing the indexed vec type "in house".

The append-only-with-no-bounds-checks `Vec` would I guess have to be a different type. But I don't think we should do that right now - I just mention it as something to have in mind for later.

**Comment by Conaclos** [comment]
> Initialize our indexed Vecs with a dummy entry at index 0, so usable indexes start at 1.

Naive question: could you not subtract the index by 1 each time you want to access the element in the array?

**Comment by overlookmotel** [comment]
> Naive question: could you not subtract the index by 1 each time you want to access the element in the array?

Yes we could, and for some use cases that would be a good solution. But personally I don't think it's ideal for ours, because:

* These vecs are typically very large, so 1 dummy entry is a drop in the ocean. Costs almost nothing.
* In comparison, read and writes are very common and on hot paths. So while subtracting 1 is a small cost (only 1 x CPU op) for each individual operation, it will add up to quite a lot in total.

Therefore, on balance, I think a dummy entry will be more performant for our use case.

Does that make sense?

**Comment by rzvxa** [comment]
I had some limited success with non-zero index here https://github.com/oxc-project/oxc/pull/3104, The Issue is that the performance gain I saw wasn't high enough for me to consider taking the risk of destabilizing index_vec with this major change.

But as our `Option<Index>` fields grow in the project we would gain more and more performance from this change.

The hard part is having to support all vector operations and its iterators, There are a lot of safety concerns to think about before switching to non zero indecis.

And some operations are slow because of safety checks, We can switch to unsafe methods in our vector so we can gain more whenever it is safe to skip the checks.
