### ISSUE TITLE
Catch panics in conformance tests

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#3497]
While working on #3489, I have been hitting conformance test cases where the transformer panics. It's difficult to debug because, while stack trace tells you where the panic arises, it doesn't tell you on which test case.

Could we make the conformance runner catch panics and report them as test fails, rather than crashing the process?

I believe we would need to:

1. Wrap running cases in `std::panic::catch_unwind`.
2. Run coverage with profile including `panic = "unwind"` instead of `panic = "abort"`.

If `panic = "unwind"` would slow down coverage a lot, could we keep `panic = "abort"` as the default but add a separate command `just coverage-with-unwind` which you can use when you are trying to debug panics?

**Comment by Boshen** [comment]
I had `catch_unwind` two years ago and it didn't work out due to `rayon` - the stack trace is hard to interpret, and it also caused stack overflow frequently as a byproduct.

How I debug this manually is remove `par_iter` and print the case sequentially, and then copy out the test case to the example run.

We can add a flag for this behavior.

**Comment by overlookmotel** [comment]
`--debug` option added in #3622.
