### ISSUE TITLE
Access `AstNodeId`s of a `AstNode`'s children

### ISSUE THREAD

**Issue by rzvxa** [oxc-project/oxc#3662]
I need a way to access `AstNodeId`s of a specific node's children. Let's say we have an `AstNode` of an `IfStatement` or `SwitchStatement`, There are times that we would want to intercept these and infer information about their children to limit a procedure to a specific scope instead of going the other way around using `ancestors` iterator.

It can be convenient to provide a way to do it without the overhead of a search. I can think of 2 ways, We could either generate a reverse hashmap between ast elements and their IDs Or add the `AstNodeId` to the ast elements to prevent the hashmap entirely.

Both of these can be feature-gated, but it's a really handy thing to have around and can provide utility even in cases where it wasn't necessary.

If anyone has a better suggestion for this please don't hesitate to pitch in!

Wouldn't it be good if we could do this?

```rust
let case_nodes = switch.cases.iter().map(|it| ctx.nodes().get_node(it.ast_node_id()));
```

Or

```rust
let case_nodes = switch.cases.iter().map(|it| ctx.get_ast_node_id(node));
```

Or even

```rust
// notice it isn't exactly the same, we get "children" instead of "cases".
let children = ctx.nodes().children_nodes(switch_node.id())
```

**Comment by rzvxa** [comment]
@Boshen @overlookmotel @Dunqing @mysteryven  any thoughts?

**Comment by Boshen** [comment]
When you have an `AstNode`

```
pub struct AstNode<'a> {
    id: AstNodeId,
    kind: AstKind<'a>,
```

you can get the ast from `kind`,

and then you can implement a visitor for the sub tree.

**Comment by Boshen** [comment]
Apparently there is an extreme case in crates/oxc_linter/src/rules/eslint/array_callback_return/return_checker.rs ...

**Comment by rzvxa** [comment]
You are right, But with that, you can only visit ast items (aka `kind`s) and not the `AstNode`s, So there is no way to access for example `cfg_id` of a given switch case, If there is let me know; I might be wrong on this.

**Comment by Boshen** [comment]
We don't have a way of getting child `AstNode`s.

This is another case for adding ast node ids to the actual ast nodes 😦

**Comment by overlookmotel** [comment]
My position has been to be pretty anti putting node IDs on every AST node. It's not an insignificant memory overhead to add to the AST, and I'm not a fan of the indirection involved.

But... I don't really know what I'm talking about! I don't know the linter at all, so I'm not sure how all these structures are used there.

A bit of background which isn't visible from Github issues: Boshen and I had a conversation about Semantic earlier this week. The gist was:

It's clear that there's a lot of room for performance improvement. Of the transformer benchmark run time, at least 60% is taken up building `Semantic`, and just *dropping* `Semantic` takes longer than the entire transformer itself.

We now have 3 different AST visitors - `Visit`, `VisitMut`, and `Traverse` - which all have different ways of referencing AST nodes, and use different parts of `Semantic`, in different ways.

I proposed that I'd like to have the opportunity to research, learn all the parts of Oxc that I don't know, and then come back with a proposal to hopefully:

1. Improve performance of `Semantic`.
2. Unify the 3 different visitors.

That will take some time (many weeks). But personally I think at this point it's preferable to try to make a plan for this whole sub-system of Oxc in a holistic "the whole picture" way, rather than making changes piecemeal. So I'd like to think about it quite deeply, and write up a proposal for discussion between everyone involved, before we move forwards.

So... in that context, personally I don't think this is the ideal time to be making a major change like adding `NodeId` to every AST node type. If there's another way to address the specific problems @rzvxa without this, I think that'd be preferable.

But if you guys feel strongly it's the way to go, and you're blocked, then feel free to ignore me and go ahead. Just please don't be too surprised if I come back next month and propose going in a different direction, and want to tear up all your work!

I hope this make sense. (NB I won't be around for next few days - off working on another project)

**Comment by rzvxa** [comment]
Thanks for filling me in on the situation. Take your time, For now, I've managed with a temporary workaround. There are a few complications I have to figure but it is manageable.

Feel free to let me know if there is anything that I can help with.

**Comment by Boshen** [comment]
Closing as for house keeping because we know there's an eventual need for ids in the ast.
