### ISSUE TITLE
Codegen AST related code

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#3819]
## Background

For keeping compilation speed down for ourselves and our downstream crate users, I have avoided using macros to generate boilerplate code at all cost.

> All performance issues (runtime and compilation speed) are considered as bugs in this project.

But due to the amount of AST related supporting code has expanded over the last few months, and our desire to experiment with different ideas with the AST, our current approach of manually updating everything is no longer functional.

The goal of this task is to provide code generation for all AST node related code.

## Requirements

* no build.rs published to the user
* all generated code are checked into git
* no nightly
* Rust code residing in `crates/oxc_ast` should be the source of truth

## Workflow

* a user changes the oxc_ast crate
* a watch change picks it up
* parse all `#[visited_node]`
* saves them into a model, e.g. `struct ASTModel { name: String, attributes: Vec<Attributes> }`
* generate code and save file

## Code to generate

- [x] `ASTKind` (Milestone 1)
- [x] `GetSpan` (Milestone 2)
- [ ] `Hash`, `PartialEq` implementations (Milestone 3)
- [x] `ASTBuilder` (Milestone 4)
- [x] `Visit` (Milestone 5)
- [x] `VisitMut` (Milestone 5)
- [ ] `Traverse`, remove current js code (Milestone 6)
* ~typescript definition for napi and wasm~ moving the scope to AST transfer.

Every milestone should be a stack of PRs, since they will involve changing other files as well.

**Comment by overlookmotel** [comment]
The AST also includes some types which are in `oxc_syntax` e.g. `AssignmentOperator`, `BinaryOperator` etc. Should we move those types into `oxc_ast` to simplify which files the codegen needs to read?

(I've never been clear why these types are in `oxc_syntax`, since they are part of AST)

**Comment by Boshen** [comment]
> The AST also includes some types which are in `oxc_syntax` e.g. `AssignmentOperator`, `BinaryOperator` etc. Should we move those types into `oxc_ast` to simplify which files the codegen needs to read?
> 
> (I've never been clear why these types are in `oxc_syntax`, since they are part of AST)

> Should we move

No, let's not scope creep.

**Comment by Boshen** [comment]
Are we able to manually inline `@inherit MemberExpression` and generate all the other utilities for these `inherit_variants!` enums?

**Comment by rzvxa** [comment]
If we want to have the inheritance expanded we should do the expansion with the codegen to keep it consistent and schema close to the ECMAspec. But manually inlining the variants is going to be a nightmare because they would easily drift apart with some time and careless reviewing(which always happens no matter how many people review the same piece of code).

**Comment by rzvxa** [comment]
> Hash, PartialEq implementations (Milestone 3)

@Boshen @overlookmotel I think we should remove this one from our milestones and here's why.

The performance gain from pre-expanding builtin derives is going to chop off a handful of seconds from our build time and even that is an optimistic estimate. It might at first feel unintuitive but let me explain myself.

### Syntax Extensions

The macro calls(including the macro_rules itself), attributes, and derives are among syntax extension kinds, A syntax extension is the last form of a macro(usually) before turning into the desired AST.

If you look at the implementation of [SyntaxExtensionKind](https://github.com/rust-lang/rust/blob/32e692681e457b06efedd05c5a4be0d718f39292/compiler/rustc_expand/src/base.rs#L669) you'd find that there are 2 kinds of any macro kind, There are 2 sets `Bang`, `Attr`, `Derive` and `LegacyBang`, `LegacyAttr`, `LegacyDerive`.

### What's the difference?

In a nutshell, legacy kinds have `AST -> AST` signature as opposed to `TokenStream -> TokenStream`.
As of right now, Rust [registers all of its builtin macros](https://github.com/rust-lang/rust/blob/32e692681e457b06efedd05c5a4be0d718f39292/compiler/rustc_builtin_macros/src/lib.rs#L69) as the latter kind, These implementations are the closest to the bare metal and get executed almost as fast as any lowering process happening in the compiler.

### What happens if they phase out the legacy kinds?

Well again it might seem intuitive that with this change a pre-expand can improve the build time by a good margin but the truth is that for dead simple macros such as these 2 if written as a procedural macro you are going to mostly wait on the initial build of the macro crate and then spend a good amount of time on the overhead of the [proc_macro_server](https://github.com/rust-lang/rust/blob/master/compiler/rustc_expand/src/proc_macro_server.rs#L417), So if they were to phase out the legacy expanders they still can implement the [MultiItemModifier](https://github.com/rust-lang/rust/blob/35b658fb1071d752d092751d9f17a9fa7b154ec4/compiler/rustc_expand/src/base.rs#L253) differently to short-circuit to the builtin implementation avoiding all of the shortcomings of normal procedural macros.

### Conclusion

I guess my conclusion is in the form of a question.
While pre-expanding the built-in derives can speed up the builds by N seconds is it really worth giving up on the built-in macros? It yields more performance if it is done on the derives implemented in the users' land.

**Comment by overlookmotel** [comment]
You make a strong case for why performance wouldn't be a good reason to codegen these 2 traits. Thanks for all the background info. I was completely unaware of the legacy macro kinds, and Rust's macro machinery in general. Really interesting.

But, just to explain, my rationale for putting these 2 on the list wasn't for perf reasons. The reasons were:

### `Hash`

We want `Hash` to skip `span` fields, and also `symbol_id` etc. Skipping `Hash` is currently achieved by a dummy `Hash` impl on `Span` type:

https://github.com/oxc-project/oxc/blob/1b91d40da26a59c353873e93483aac58c4ac9f39/crates/oxc_span/src/span.rs#L309-L313

I saw this as a bit of a hack, and thought it would be more "proper" solution to implement `Hash` on all AST types with the `span` field explicitly skipped. That would be laborious and error-prone to do by hand, but much easier with codegen.

### `PartialEq`

The reason why we are implementing `Hash` on AST types is for (if I remember right) comparing expressions in a lint rule to identify pointless `if` branches e.g. `if (x) {} else if (x) { /* unreachable */ }`. But actually `Hash` is not ideal for this use - `PartialEq` would be more efficient.

But it's hard to implement `PartialEq` because, again, we need to skip `span` fields, and the no-op hash hack isn't viable here, so we can't use `#[derive(PartialEq)]`.

So I thought we could do that with codegen.

### Conclusion

I'm not at all arguing against what you've said @rzvxa. I just wanted to explain that there was another angle.

**Comment by rzvxa** [comment]
Thanks for the explanation, Now I see the full picture for this one.

**Comment by Boshen** [comment]
We can defer the implementation of `Hash` and `PartialEq` because we don't need them right now (we didn't need them for so long so probably won't need them for a longer time.)

As for `Traverse`, @rzvxa can decide continue working on it, or come back after research for ast template macro is completed.

**Comment by Boshen** [comment]
Consider this is done, we can migrate `Traverse` at a later time, and raise new issues regarding ast codegen.
