### ISSUE TITLE
An error occurred when running oxlint using child_process

### ISSUE THREAD

**Issue by lifengsbotlp** [oxc-project/oxc#4525]
1. An error occurred when running oxlint using child_process. Take a look at the following two diagrams for detailed usage and error information.
<img width="410" alt="image" src="https://github.com/user-attachments/assets/cc73e2f6-3801-446b-8f63-059599b289b9">
<img width="371" alt="image" src="https://github.com/user-attachments/assets/0b9996a3-2949-4175-819f-991207ae8655">
2. If you execute npx oxlint directly on the terminal, everything is fine
3. oxlint has been installed locally with version "oxlint": "^0.6.1"

**Comment by rzvxa** [comment]
I think it is the intended behavior, Correct me if I'm wrong; You are lining code that is producing errors. We return exit code `1` if we have any lint errors(or warnings if `deny warnings` is on).

So oxlint is running correctly, Encounters linting issues, and returns the exit code 1, Any process that doesn't return 0 at the end of execution means it exits with errors. And that's why I believe it is the correct behavior.

**Comment by lifengsbotlp** [comment]
> 我认为这是预期的行为，如果我错了，请纠正我；
> 
> 1. 您正在编写产生错误的代码。
> 2. `1`如果有任何 lint 错误（或打开时为警告），我们将返回退出代码`deny warnings`。
> 
> 因此，oxlint 运行正常，遇到 linting 问题，并返回退出代码 1，任何在执行结束时未返回 0 的进程都意味着它会因错误而退出。这就是我相信这是正确行为的原因。

> I found an article on stackoverflow with the same question. That's what I'm dealing with right now.
https://stackoverflow.com/questions/61231106/why-is-my-exec-command-failing-but-works-if-the-command-is-passed-in-the-te rmina
