### ISSUE TITLE
feat(linter): no-redeclare implementation

### ISSUE THREAD

**Issue by eryue0220** [oxc-project/oxc#520]
This issue is used for tracking the rule implementation. 

The rule detail:  https://eslint.org/docs/latest/rules/no-redeclare

**Comment by Boshen** [comment]
For no-redeclare, we are going to deviate the implementation from ESLint, because we have the compiler!

To get started, take a look at this line:

https://github.com/Boshen/oxc/blob/6428139b7603c11b3b05d3cb0cc8ae84ed8435ef/crates/oxc_semantic/src/binder.rs#L43-L45

And find yourself a way store the redeclared information into `Semantic`, probably just a vector of relevant information, e.g. a struct `RedeclaredSomething`

And then in your rule, test against `Program` to get the rule to only run once, and then read the information and print them out.

**Comment by eryue0220** [comment]
Thanks a lot, I'll try.

**Comment by IWANABETHATGUY** [comment]
closed in favor of https://github.com/oxc-project/oxc/pull/683
