### ISSUE TITLE
Add `ThisExpression` variants to `JSXElementName` and `JSXMemberExpressionObject`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#5352]
#5223 did the bulk of the work of revamping `JSXElementName` (#3528). Only thing that's missing is to add:

* `JSXElementName::ThisExpression`
* `JSXMemberExpressionObject::ThisExpression`

A couple of notes:

#### Arrow functions transform

This code is currently broken:

https://github.com/oxc-project/oxc/blob/f052a6d6664b4bfa3fae14445ce7558f8186e0c1/crates/oxc_transformer/src/es2015/arrow_functions.rs#L140-L156

We can fix after we have the `ThisExpression` variants.

#### Linter

Once this is done, we can remove these lines from linter.

https://github.com/oxc-project/oxc/blob/f052a6d6664b4bfa3fae14445ce7558f8186e0c1/crates/oxc_linter/src/rules/react/jsx_no_undef.rs#L60-L64

**Comment by Dunqing** [comment]
Before doing this, we can do some preparation work here

https://github.com/oxc-project/oxc/blob/93634bc2c80ca6f3ddc116ec5558a8e700f91db7/crates/oxc_transformer/src/es2015/arrow_functions.rs#L134-L170

We should mutate node instead of mutating the node property. Because after `JSXElementName::ThisExpression` was added, we need to transform `JSXElementName::ThisExpression` to `JSXElementName::IdentifierReference` so that we must mutate the node itself.

**Comment by overlookmotel** [comment]
I think we were having the same thought simultaneously! https://github.com/oxc-project/oxc/pull/5356#pullrequestreview-2273108022
