### ISSUE TITLE
Transform: Tab `\t` in JSX should be trimmed

### ISSUE THREAD

**Issue by magic-akari** [oxc-project/oxc#6638]
[OXC playground](https://oxc-project.github.io/oxc/playground/?code=3YCAAIDcgYCAgICAgICyHorESipoTXg5tGjCQfrkttQjp%2BeydgrtwPxXWnKjfGJOpOItqQuFiwzy7SfXue0uloeaWYLNd3DtKjmvp1cYlWCbw2DxU%2FrgLsrAO4E8Wiu0Nr02kKm0lOQJh%2BQ%2BShYXYge9zaPLAXv3xvOc3pdePtmwzid4Ii1mEQo0ZC6KamShhMEBcTav8ibwZKjs8tv5uIYGW6zJcNe7ORvrlGsYw6fbkj6hfjm6e70V14jYFUgS7yNKWtTAEJAqF4fcYQHvxWSMnR5WeF9oYVBlHBJCd%2BRFJ0UleeHATGEDqHr0974%3D)

**Comment by overlookmotel** [comment]
I *think* this should be fixed in parser (not transformer). I don't think we should have had nodes like this in the AST in the first place:

```rs
JSXText {
    span: Span { start: 68, end: 72 },
    value: "\n\t\t\t",
}
```

@Boshen can you confirm I am right about that?

**Comment by magic-akari** [comment]
> I _think_ this should be fixed in parser (not transformer). I don't think we should have had nodes like this in the AST in the first place:
> 
> ```rust
> JSXText {
>     span: Span { start: 68, end: 72 },
>     value: "\n\t\t\t",
> }
> ```
> 
> @Boshen can you confirm I am right about that?

When I attempted to fix the issue, I suspected the parser. 
But upon examining the AST outputs from both TypeScript and Babel, I discovered that they were both present in the AST.

When I tried to fix it, I suspected the parser might be the issue. 
However, after reviewing the AST outputs from both TypeScript and Babel, I realized that they arre preserved in the AST.

**Comment by overlookmotel** [comment]
Re-opening as would like @Boshen's view on whether parser should be producing these `JSXText` elements which contain only whitespace.

If I remember right, we decided that our support for JSX is limited to React JSX (and React-like JSX, e.g. Vue), rather than attempting to follow the full "abstract" JSX spec. Therefore, even if JSX spec says these `JSXText` nodes should be present, I don't think that's relevant.

In React JSX (and ditto Vue) whitespace in these positions is not semantically meaningful. We don't use a Concrete Syntax Tree so, like other semantically-meaningless whitespace, personally I don't think this should appear in the AST.

It's not purely an academic question. In typical React/Vue/etc code, our AST will contain a *lot* of these pointless `JSXText` nodes. It may well has a measurable perf impact. @magic-akari's [simple example](https://oxc-project.github.io/oxc/playground/?code=3YCAAIDcgYCAgICAgICyHorESipoTXg5tGjCQfrkttQjp%2BeydgrtwPxXWnKjfGJOpOItqQuFiwzy7SfXue0uloeaWYLNd3DtKjmvp1cYlWCbw2DxU%2FrgLsrAO4E8Wiu0Nr02kKm0lOQJh%2BQ%2BShYXYge9zaPLAXv3xvOc3pdePtmwzid4Ii1mEQo0ZC6KamShhMEBcTav8ibwZKjs8tv5uIYGW6zJcNe7ORvrlGsYw6fbkj6hfjm6e70V14jYFUgS7yNKWtTAEJAqF4fcYQHvxWSMnR5WeF9oYVBlHBJCd%2BRFJ0UleeHATGEDqHr0974%3D) has 11 `JSXText` nodes in it.

**Comment by Boshen** [comment]
The parser is correct according to the spec https://facebook.github.io/jsx/#prod-JSXText

The transformer is responsible for how to deal with these whitespaces, which is also correct, because our jsx transform is correct.
