### ISSUE TITLE
transformer: a helper for inserting new statements above or below the current statement.

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#6641]
Unified usage like https://github.com/oxc-project/oxc/issues/4767#issue-2456217141 does

**Comment by overlookmotel** [comment]
Good idea.

As #6644 is problematic, I suggest using `Address` as the unique ID.

https://github.com/oxc-project/oxc/blob/92812349e5266b074d2cb050cc7a6f200e4ac914/crates/oxc_allocator/src/boxed.rs#L173-L181

Currently we only support getting an `Address` for a `Box`, but we can also support getting `Address` for a `&Statement`:

```rs
pub trait GetAddress {
    fn address(&self) -> Address;
}

impl<'a> GetAddress for &Statement<'a> {
    #[inline]
    fn address(&self) -> Address {
        match self {
            Statement::BlockStatement(s) => s.address(),
            Statement::BreakStatement(s) => s.address(),
            Statement::ContinueStatement(s) => s.address(),
            // ... all the rest
        }
    }
}
```

The `match` will be massive, but compiler should boil it all down to a single assembler instruction - it's very efficient.

We could generate this with `oxc_ast_tools`. But if that's too much faff, could also just write it out manually.

I know everyone but me sees `Address` as a hack, but it's really not. It's a fundamental of things in memory that they have a memory address! Why not utilize that?

**Comment by overlookmotel** [comment]
`Address` represents the memory address of the `Statement`'s *contents*, not the `Statement` itself. i.e. for `Statement::BlockStatement`, `stmt.address()` gives you memory address of the `BlockStatement`, not the `Statement`.

`Statement` consists of:

1. Enum discriminant - 1 byte, which says what *type* of statement it is.
2. A `Box<T>` - the "payload" e.g. `Box<BlockStatement>`.

`Box` is just a pointer. So you can move a `Box`, and its contents don't move - the *pointer* has moved, but it's still *pointing to* the same place.

Therefore, you can also move a `Statement`, and the "payload" (e.g the `BlockStatement`) doesn't move. So the `Address` doesn't change, because the `BlockStatement` is still in the same place.

So, how does this apply to `Vec<Statement>`?

`Vec<Statement>` is an array of `Statement`s. As discussed above, you can move `Statement`s around, and `stmt.address()` will still give you the same result. `Vec::drain`, `Vec::retain`, `Vec::insert` etc shuffle the `Statement`s around in memory, but they don't move the *contents* of the statements. So those methods will not alter `Address`es.

```rs
let mut stmts = Vec::new_in(allocator);

stmts.push(Statement::EmptyStatement(Box::new_in(
    EmptyStatement { span: Span::new(0, 0) },
    allocator,
)));

// Get address of the statement at index 0
let address = stmts[0].address();

// Insert another statement before it
stmts.insert(
    0,
    Statement::EmptyStatement(Box::new_in(EmptyStatement { span: Span::new(1, 1) }, allocator)),
);

// The original statement is now to index 1,
// but its `Address` has not changed
assert_eq!(stmts[1].address(), address);
```

Mutating a `BlockStatement`, `Function` etc in place will also not change its `Address`.

The only thing that *will* affect `Address` is if you replace a `Statement` with a *new* `Statement`.

If you take ownership of a `Statement`, unbox it, and then reallocate it into the arena again, that will also affect `Address`, because essentially it's the same as replacing the `Statement` with a new one. But I don't think we do that anyway, and if we do, we shouldn't because that's inefficient - why create a new `Statement` when you can just mutate the existing one?

So... TLDR... I think `Address` should gives us what we need for this.

**Comment by Dunqing** [comment]
@overlookmotel I got your point, I am trying it

**Comment by Dunqing** [comment]
Here a case can be replaced with `StatementInjector` (#6653). But I'm stuck on how to get `address` by `Ancestor`
https://github.com/oxc-project/oxc/blob/ca8c578932734329ee753ca5eb814029a4714e64/crates/oxc_transformer/src/react/refresh.rs#L269-L304

The above logic handles the following code, ￼and determines whether the parent of the current node is ⁠`Ancestor::VariableDeclaratorInit`, if yes, transform and add a new statement to `self.extra_statements`

```ts
const statement = function b() {}
```

I want to use `StatementInjector` to replace `self.extra_statements`, so I need to get the `Address` of `Statement::VariableDeclaration` by `Ancestor`

Do you think it is possible?

**Comment by overlookmotel** [comment]
I *think* it should be possible to add support for getting `Address` from an `Ancestor` without UB. I'll try and figure that out.

**Comment by Dunqing** [comment]
> I _think_ it should be possible to add support for getting `Address` from an `Ancestor` without UB. I'll try and figure that out.

I have created a [issue](https://github.com/oxc-project/oxc/issues/6803) to track down this.

closing as this helper has introduced in #6653
