### ISSUE TITLE
transformer: typescript `--useDefineForClassFields`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#6735]
https://www.typescriptlang.org/tsconfig/#useDefineForClassFields

https://babeljs.io/docs/babel-plugin-transform-typescript
* --useDefineForClassFields You can use the [setPublicClassFields](https://babeljs.io/docs/assumptions#setpublicclassfields) assumption to replicate this behavior.

https://github.com/oxc-project/oxc/blob/aa3222ac88566e50bd4858561aeb056db973224b/crates/oxc_transformer/src/compiler_assumptions.rs#L50

**Comment by Boshen** [comment]
Done in https://github.com/oxc-project/oxc/pull/7011 with `setPublicClassFields`.

**Comment by sapphi-red** [comment]
@Boshen Can we reopen this issue as the transform is now disabled? (#7486)
Or should I check https://github.com/oxc-project/oxc/issues/4754?

**Comment by sapphi-red** [comment]
Is there a way to transform public fields with `useDefineForClassFields: false` and also keep other class field features as-is? For example, when a user has `useDefineForClassFields: false` and `target: 'es2024'`.

**Comment by Boshen** [comment]
> Is there a way to transform public fields with `useDefineForClassFields: false` and also keep other class field features as-is? For example, when a user has `useDefineForClassFields: false` and `target: 'es2024'`.

Not at present.

**Comment by overlookmotel** [comment]
> Is there a way to transform public fields with `useDefineForClassFields: false` and also keep other class field features as-is? For example, when a user has `useDefineForClassFields: false` and `target: 'es2024'`.

What's the use case for transforming public fields, but not private fields?

**Comment by sapphi-red** [comment]
> > Is there a way to transform public fields with `useDefineForClassFields: false` and also keep other class field features as-is? For example, when a user has `useDefineForClassFields: false` and `target: 'es2024'`.
> 
> What's the use case for transforming public fields, but not private fields?

When a library you depend relies on the `useDefineForClassFields: false` behavior, but you don't need to transpile everything down to es2021. TypeScript and esbuild both supports this: [typescript playground](https://www.typescriptlang.org/play/?target=11&useDefineForClassFields=false#code/MYewdgzgLgBATgUxgXhgegIZoG4ChfAA2GEEMAwjAN64wwDEADnCjAAwDc+dAZiCKwCMbTrRgAjDHABcMaHACWYAOYwAPjACuYACYIeShDq4BfXEA), [esbuild try](https://esbuild.github.io/try/#dAAwLjI0LjAAewogIGxvYWRlcjogJ3RzJywKICB0YXJnZXQ6ICdlczIwMjMnLAogIHRzY29uZmlnUmF3OiB7CiAgICBjb21waWxlck9wdGlvbnM6IHsKICAgICAgdGFyZ2V0OiAnZXMyMDIzJywKICAgICAgdXNlRGVmaW5lRm9yQ2xhc3NGaWVsZHM6IGZhbHNlLAogICAgfSwKICB9LAp9AGNvbnN0IHJlID0gL2EvdgoKY2xhc3MgQyB7CiAgZm9vID0gMTAwOwogIGJhcjogc3RyaW5nOwp9)
I don't have a real world case, but I guess there are, because [angular sets this](https://github.com/angular/angular-cli/blob/main/CHANGELOG.md#angular-devkitbuild-angular-92:~:text=Internally%20the%20Angular%20CLI%20now%20always%20set%20the%20TypeScript%20target%20to%20ES2022%20and%20useDefineForClassFields%20to%20false%20unless%20the%20target%20is%20set%20to%20ES2022%20or%20later%20in%20the%20TypeScript%20configuration.%20To%20control%20ECMA%20version%20and%20features%20use%20the%20Browerslist%20configuration.) by default and [lit suggests](https://lit.dev/docs/components/decorators/#decorators-typescript) to set it.

**Comment by sapphi-red** [comment]
Both angular and lit sets `useDefineForClassFields: false` to make decorators work nicely so I guess it won't be a problem until decorators are supported by oxc. I think I can just set the target to es2021 and show a warning that the target was changed for now. Vite has been recommending setting `useDefineForClassFields: true` regardless of the target and that should reduce the number of affected users.

**Comment by overlookmotel** [comment]
Just FYI, in case it wasn't clear: Any code which contains decorators currently will not run, because Oxc doesn't transform decorators, and most JS runtimes don't support decorators natively. `useDefineForClassFields` will not save us!
