### ISSUE TITLE
linter: rule incorrectly reported as unmatched

### ISSUE THREAD

**Issue by camchenry** [oxc-project/oxc#7025]
I wonder why I got this with config: `"no-default-export": "allow"`,

> oxlint Stderr:   ! The following rules do not match the currently supported rules:
>   | no-default-export

when `oxlint --rules` have this rule in the list under Restriction category (on `0.10.3`)

originally reported by `@ariu` on discord

**Comment by arnriu** [comment]
Thank you. I would add this comment also, because I don't think rule is incorrectly reported, I believe rule is not there at all:


If I just remove `"no-default-export": "allow"` from my oxlintrc , then I do not have this message. But oxlint says `Found 0 warnings and 0 errors.` with `"restriction": "error",` , and I can tell you with certainty that my codebase have a lot of default exports.
**It's like this rule is not there anymore**

**Comment by camchenry** [comment]
@arnriu I improved the unmatched rule code yesterday, I think this should resolve any other potential issues with the rule being reported as not existing.

Make sure that you are passing `--import-plugin` in the CLI, or passing `"plugins": ["import"]` in the config (plus whatever other plugins you are using), otherwise the rule will not be run.
