### ISSUE TITLE
codegen: remove underscore from bigint

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#7285]
> https://github.com/oxc-project/oxc/blob/44375a5662ee3e6451f1a5335c75d6379d1878a6/crates/oxc_codegen/src/gen.rs#L1171
> 
> looks like it prints the raw val from the original source text

Good catch, underscore should be removed from codegen.

_Originally posted by @Boshen in https://github.com/oxc-project/oxc/issues/7280#issuecomment-2476817690_

**Comment by overlookmotel** [comment]
Please also see #7254. Of the options outlined there, personally I'd tend towards the option of removing the `raw` field.

In my view, the ideal solution would be to parse the BigInt's value in the parser. At that point we are running through the source text byte-by-byte anyway.

I would propose:

* Adding a `value: &'a str` field.
* Removing the `base` field.

```rs
pub struct BigIntLiteral<'a> {
    pub span: Span,
    pub value: &'a str,
    pub raw: &'a str, // Leave for now, but likely remove later
}
```

In parser, parse it to a `&str` (without underscores, converted to decimal), using code like this:

https://github.com/oxc-project/oxc/blob/f0affa20c62d21d927b0a80961f9519d55f626e1/crates/oxc_ast/src/serialize.rs#L68-L93

Then codegen can print the `value` field.

A bit of background: Originally `BigIntLiteral` had a `value: BigInt` field. We had to remove it because `BigInt` stores data on the heap, so it's not possible to make it part of the AST, as that heap data didn't get freed when the AST is dropped (memory leak). So that's why we have to store the value as a string slice (which would be stored in arena).

However, removing the underscores in codegen is an improvement on how it is now - not a bad interim solution.
