### ISSUE TITLE
When I use traverse_mut to traverse nodes, I want to create a expression_function node. When I create and replace successfully, an error occurs, do I need to manually create a scopeId for the newly created function node? How should I fix this？

### ISSUE THREAD

**Issue by JasithC** [oxc-project/oxc#7580]
![image](https://github.com/user-attachments/assets/91d8b545-64fe-41ef-a948-c2d20bed16b9)
![image](https://github.com/user-attachments/assets/50f923f9-2790-4fed-bbf6-c06695c189e2)
The error message is here

**Comment by JasithC** [comment]
![image](https://github.com/user-attachments/assets/774245f4-2705-4944-95ad-1c31cbe49a08)

**Comment by overlookmotel** [comment]
Yes. When creating a new function, you need to create a new scope for it too.

`TraverseCtx::create_child_scope_of_current` is probably what you need:

https://github.com/oxc-project/oxc/blob/f0e7acc68b3509ff1f50e760d0bd342999979057/crates/oxc_traverse/src/context/mod.rs#L249-L257

Create the scope first, and then set the `ScopeId` for the function when you create it. Use `Expression::FunctionExpression(ctx.ast.alloc_function_with_scope_id(...))` to create the function, so you can provide the `ScopeId`.

I'm not sure what the overall purpose of your code is, but also you should be able to condense it down a lot. There should be no need for all these `ctx.alloc` and `clone_in` calls.

`clone_in` will likely cause you the same kind of problems, because it wipes all the `scope_id`, `symbol_id` and `reference_id` fields. `clone_in` is best avoided for this reason.

**Comment by JasithC** [comment]
My intent is to simplify the js code, like
 var p = function() {
	return [function(a) {
		console.log(a);
	}];
};
Simplified to
 var p = {"1": function(a) {
		console.log(a);
	}}
The purpose of using clone_in is to copy a whole fucntion, if I want to carry the scopeId, can't I use the ctx.ast.expression_function to create a new function node?

**Comment by overlookmotel** [comment]
I've edited your comment above to make it more readable. I don't mean to be rude, but we have limited resources. Please help us to help you by posing your question in a way that makes it as easy to understand for us as possible.

You don't need to clone the function, because you only have 1 copy of it in the output.

Please look at the `move_*` methods in [`AstBuilder`](https://github.com/oxc-project/oxc/blob/f0e7acc68b3509ff1f50e760d0bd342999979057/crates/oxc_ast/src/ast_builder_impl.rs). Those allow you to "take" the existing function, and then you can insert it somewhere else in the AST. No need to make a copy of it, just move it.

**Comment by overlookmotel** [comment]
I'm going to close this issue because issues are for bug reports, not help requests.

Please ask on [our Discord](https://discord.gg/9uXCAwqQZW) where there are many people who will be happy to help you.

**Comment by JasithC** [comment]
How Should I Join Your Discord?

**Comment by JasithC** [comment]
Why can't I find this method `ctx.ast.alloc_function_with_scope_id`
