### ISSUE TITLE
Version 0.39 oxc_traverse cannot use walk_program

### ISSUE THREAD

**Issue by anguish-huihuang** [oxc-project/oxc#7694]
Is the walk_program method of oxc_traverse 0.39 no longer usable? Then how can I repeat the Traverse method implemented by traversing the structure in the enter_program method? This is my original writing method.
`impl<'a> Traverse<'a> for ConstantReplace { fn enter_program(&mut self, node: &mut Program<'a>, ctx: &mut TraverseCtx<'a>) { let constant_define = &mut ConstantDefine{ var_info: HashMap::new() }; walk_program(constant_define, node, ctx); let constant_replace = &mut ArrayReplace { var_info: constant_define.var_info.clone() }; walk_program(constant_replace, node, ctx); walk_program(constant_replace, node, ctx); let function_define = &mut FunctionDefine { function_var: ctx.ast.vec(), scope_id: ScopeId::new(0) }; walk_program(function_define, node, ctx); let function_replace = &mut FunctionReplace { function_var: std::mem::replace( &mut function_define.function_var, ctx.ast.vec()), len: 0, symbol_id: HashSet::new() }; walk_program(function_replace, node, ctx); let computer_member_replace = &mut ComputerMemberReplace {symbol_id: function_replace.symbol_id.clone()}; walk_program(computer_member_replace, node, ctx); // let function_replace = &mut FunctionReplace { var_fun_info: oxc::allocator::Vec::new_in(&allocator) }; // println!("span:{:#?}", node); } }`

**Comment by Boshen** [comment]
See https://github.com/oxc-project/oxc/blob/5f4f6d140bde634eeda4705dab5db82cde817e2a/crates/oxc_minifier/src/compressor.rs#L36

**Comment by Dunqing** [comment]
You can access scopes and symbols by the third parameter of `enter_program`. Please refer to https://github.com/oxc-project/oxc/blob/main/crates/oxc_transformer/src/lib.rs

**Comment by overlookmotel** [comment]
@anguish-huihuang I have reformatted your code example. Please post code which is actually readable. It's very hard to help you when we can't understand what you're doing.

`walk_program` had to be removed because it was unsound. In fact, the unsound usage we needed to prevent was exactly what you're doing here.

Anyway, I don't think you need `walk_program` to achieve what you're trying to do. Please look at the existing transforms in `oxc_transformer` to see how we compose different transforms.

Or, if you really need each of these stages to run in series, do each as a separate traversal (i.e. call `traverse_mut` multiple times).
